"""empty message

Revision ID: 098fb88ca508
Revises: 49da331646b3
Create Date: 2024-05-17 20:26:13.529722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098fb88ca508'
down_revision = '49da331646b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.String(), nullable=True),
    sa.Column('followee_id', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
