"""empty message

Revision ID: 498861aa4c1b
Revises: 350323daf78b
Create Date: 2024-05-10 17:46:46.144502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498861aa4c1b'
down_revision = '350323daf78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
